-- SQL Server Script
-- Generated by ChatGPT
-- Date: 2023-09-27

-- Use the 'master' database
USE master;
GO

-- Drop the database if it already exists
IF EXISTS (SELECT * FROM sys.databases WHERE name = 'mydb')
    DROP DATABASE mydb;
GO

-- Create the 'mydb' database
CREATE DATABASE mydb;
GO

-- Use the 'mydb' database
USE mydb;
GO

-- Table 'user'
CREATE TABLE [dbo].[user] (
    [email] NVARCHAR(320) NOT NULL,
    [username] NVARCHAR(30) NOT NULL,
    [password] NVARCHAR(20) NOT NULL,
    [first_name] NVARCHAR(50) NOT NULL,
    [last_name] NVARCHAR(50) NOT NULL,
    [address] NVARCHAR(255) NOT NULL,
    [phone_number] NVARCHAR(15) NOT NULL,
    [last_login_time] DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT [PK_user] PRIMARY KEY ([email]),
    CONSTRAINT [UQ_Username] UNIQUE ([username])
);
GO

-- Table 'product'
CREATE TABLE [dbo].[product] (
    [code] CHAR(12) NOT NULL,
    [name] NVARCHAR(100) NOT NULL,
    [description] TEXT NOT NULL,
    [manufacturer] NVARCHAR(100) NOT NULL,
    [photo] NVARCHAR(1000),
    [price] DECIMAL(7,2) NOT NULL,
    [cost] DECIMAL(7,2) NOT NULL,
    [inventory_quantity] INT NOT NULL DEFAULT 0,
    CONSTRAINT [PK_product] PRIMARY KEY ([code])
);
GO

-- Table 'review'
CREATE TABLE [dbo].[review] (
    [review_id] INT IDENTITY(1,1) NOT NULL,
    [review_text] TEXT NOT NULL,
    [review_time] DATETIME NOT NULL DEFAULT GETDATE(),
    [email] NVARCHAR(320) NOT NULL,
    [code] CHAR(12) NOT NULL,
    CONSTRAINT [PK_review] PRIMARY KEY ([review_id]),
    CONSTRAINT [FK_review_user] FOREIGN KEY ([email]) REFERENCES [dbo].[user] ([email]),
    CONSTRAINT [FK_review_product] FOREIGN KEY ([code]) REFERENCES [dbo].[product] ([code])
);
GO

-- Table 'payment_method'
CREATE TABLE [dbo].[payment_method] (
    [payment_id] INT IDENTITY(1,1) NOT NULL,
    [name] NVARCHAR(30) NOT NULL,
    [card_number] CHAR(16) NOT NULL,
    [expiry_date] CHAR(4) NOT NULL,
    [csc] CHAR(4) NOT NULL,
    [billing_address] NVARCHAR(255) NOT NULL,
    [email] NVARCHAR(320) NOT NULL,
    CONSTRAINT [PK_payment_method] PRIMARY KEY ([payment_id]),
    CONSTRAINT [FK_payment_method_user] FOREIGN KEY ([email]) REFERENCES [dbo].[user] ([email])
);
GO

-- Table 'purchase'
CREATE TABLE [dbo].[purchase] (
    [purchase_id] INT IDENTITY(1,1) NOT NULL,
    [total_price] DECIMAL(13,2) NOT NULL DEFAULT 1,
    [purchase_time] DATETIME NOT NULL DEFAULT GETDATE(),
    [product_time] DECIMAL(7,2) NOT NULL,
    [product_quantity] INT NOT NULL,
    [payment_id] INT NOT NULL,
    [email] NVARCHAR(320) NOT NULL,
    CONSTRAINT [PK_purchase] PRIMARY KEY ([purchase_id]),
    CONSTRAINT [FK_purchase_payment_method] FOREIGN KEY ([payment_id]) REFERENCES [dbo].[payment_method] ([payment_id]),
    CONSTRAINT [FK_purchase_user] FOREIGN KEY ([email]) REFERENCES [dbo].[user] ([email])
);
GO

-- Table 'user_address'
CREATE TABLE [dbo].[user_address] (
    [email] NVARCHAR(320) NOT NULL,
    [street_address] NVARCHAR(255) NOT NULL,
    [apartment] NVARCHAR(20) NOT NULL DEFAULT GETDATE(),
    [city] NVARCHAR(100) NOT NULL,
    [state] CHAR(2) NOT NULL,
    [postal_code] CHAR(5) NOT NULL,
    CONSTRAINT [PK_user_address] PRIMARY KEY ([email]),
    CONSTRAINT [FK_user_address_user] FOREIGN KEY ([email]) REFERENCES [dbo].[user] ([email])
);
GO

-- Table 'product_has_purchase'
CREATE TABLE [dbo].[product_has_purchase] (
    [code] CHAR(12) NOT NULL,
    [purchase_id] INT NOT NULL,
    CONSTRAINT [PK_product_has_purchase] PRIMARY KEY ([code], [purchase_id]),
    CONSTRAINT [FK_product_has_purchase_product] FOREIGN KEY ([code]) REFERENCES [dbo].[product] ([code]),
    CONSTRAINT [FK_product_has_purchase_purchase] FOREIGN KEY ([purchase_id]) REFERENCES [dbo].[purchase] ([purchase_id])
);
GO
