-- MySQL Script generated by MySQL Workbench
-- Sun Jan  7 19:11:52 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `email` VARCHAR(320) NOT NULL,
  `username` VARCHAR(30) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `phone_number` VARCHAR(15) NOT NULL,
  `last_login_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE INDEX `Username_UNIQUE` (`username` ASC) VISIBLE,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product` (
  `code` CHAR(12) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT NOT NULL,
  `manufacturer` VARCHAR(100) NOT NULL,
  `photo` VARCHAR(1000) NULL,
  `price` DECIMAL(7,2) NOT NULL,
  `cost` DECIMAL(7,2) NOT NULL,
  `inventory_quantity` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`review` (
  `review_id` INT NOT NULL AUTO_INCREMENT,
  `review_text` TEXT NOT NULL,
  `review_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `email` VARCHAR(320) NOT NULL,
  `code` CHAR(12) NOT NULL,
  PRIMARY KEY (`review_id`),
  INDEX `fk_review_user1_idx` (`email` ASC) VISIBLE,
  INDEX `fk_review_product1_idx` (`code` ASC) VISIBLE,
  CONSTRAINT `fk_review_user1`
    FOREIGN KEY (`email`)
    REFERENCES `mydb`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_review_product1`
    FOREIGN KEY (`code`)
    REFERENCES `mydb`.`product` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`payment_method`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`payment_method` (
  `payment_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `card_number` CHAR(16) NOT NULL,
  `expiry_date` CHAR(4) NOT NULL,
  `csc` CHAR(4) NOT NULL,
  `billing_address` VARCHAR(255) NOT NULL,
  `email` VARCHAR(320) NOT NULL,
  PRIMARY KEY (`payment_id`),
  INDEX `fk_payment_method_user1_idx` (`email` ASC) VISIBLE,
  CONSTRAINT `fk_payment_method_user1`
    FOREIGN KEY (`email`)
    REFERENCES `mydb`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`purchase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`purchase` (
  `purchase_id` INT NOT NULL AUTO_INCREMENT,
  `total_price` DECIMAL(13,2) NOT NULL DEFAULT 1,
  `purchase_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `product_price` DECIMAL(7,2) NOT NULL,
  `product_quantity` INT NOT NULL,
  `payment_id` INT NOT NULL,
  `email` VARCHAR(320) NOT NULL,
  PRIMARY KEY (`purchase_id`),
  INDEX `fk_purchase_payment_method1_idx` (`payment_id` ASC) VISIBLE,
  INDEX `fk_purchase_user1_idx` (`email` ASC) VISIBLE,
  CONSTRAINT `fk_purchase_payment_method1`
    FOREIGN KEY (`payment_id`)
    REFERENCES `mydb`.`payment_method` (`payment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_purchase_user1`
    FOREIGN KEY (`email`)
    REFERENCES `mydb`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_address` (
  `email` VARCHAR(320) NOT NULL,
  `street_address` VARCHAR(255) NOT NULL,
  `address_line_optional` VARCHAR(100) NULL,
  `city` VARCHAR(100) NOT NULL,
  `state` ENUM('AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY', 'DC', 'PR', 'VI', 'GU', 'MP', 'AS') NOT NULL,
  `postal_code` CHAR(5) NOT NULL,
  PRIMARY KEY (`email`),
  CONSTRAINT `fk_user_address_user`
    FOREIGN KEY (`email`)
    REFERENCES `mydb`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`purchase_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`purchase_product` (
  `purchase_id` INT NOT NULL,
  `code` CHAR(12) NOT NULL,
  PRIMARY KEY (`purchase_id`, `code`),
  INDEX `fk_product_has_purchase_purchase1_idx` (`purchase_id` ASC) VISIBLE,
  INDEX `fk_product_has_purchase_product1_idx` (`code` ASC) VISIBLE,
  CONSTRAINT `fk_product_has_purchase_product1`
    FOREIGN KEY (`code`)
    REFERENCES `mydb`.`product` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_purchase_purchase1`
    FOREIGN KEY (`purchase_id`)
    REFERENCES `mydb`.`purchase` (`purchase_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
