-- MySQL Script generated by MySQL Workbench
-- Mon Jan 15 18:15:03 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`payment_method`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`payment_method` (
  `payment_id` INT PRIMARY KEY,
  `name` VARCHAR(30),
  `card_number` CHAR(16),
  `expiry_date` CHAR(4),
  `csc` CHAR(4),
  `billing_address` VARCHAR(255),
  `email` VARCHAR(320),
  CONSTRAINT `fk_payment_method_user1`
    FOREIGN KEY (`email`)
    REFERENCES `mydb`.`user` (`email`)
  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product` (
  `code` CHAR(12) PRIMARY KEY,
  `name` VARCHAR(100),
  `description` TEXT,
  `manufacturer` VARCHAR(100),
  `photo` VARCHAR(1000),
  `price` DECIMAL(7,2),
  `cost` DECIMAL(7,2),
  `inventory_quantity` INT
  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`purchase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`purchase` (
  `purchase_id` INT PRIMARY KEY,
  `total_price` DECIMAL(13,2),
  `purchase_time` TIMESTAMP,
  `product_price` DECIMAL(7,2),
  `product_quantity` INT,
  `payment_id` INT,
  `email` VARCHAR(320),
  CONSTRAINT `fk_purchase_payment_method1`
    FOREIGN KEY (`payment_id`)
    REFERENCES `mydb`.`payment_method` (`payment_id`),
  CONSTRAINT `fk_purchase_user1`
    FOREIGN KEY (`email`)
    REFERENCES `mydb`.`user` (`email`)
  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`purchase_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`purchase_product` (
  `purchase_id` INT,
  `code` CHAR(12),
  PRIMARY KEY (`purchase_id`, `code`),
  CONSTRAINT `fk_product_has_purchase_product1`
    FOREIGN KEY (`code`)
    REFERENCES `mydb`.`product` (`code`),
  CONSTRAINT `fk_product_has_purchase_purchase1`
    FOREIGN KEY (`purchase_id`)
    REFERENCES `mydb`.`purchase` (`purchase_id`)
  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`review` (
  `review_id` INT PRIMARY KEY,
  `review_text` TEXT,
  `review_time` TIMESTAMP,
  `email` VARCHAR(320),
  `code` CHAR(12),
  CONSTRAINT `fk_review_user1`
    FOREIGN KEY (`email`)
    REFERENCES `mydb`.`user` (`email`),
  CONSTRAINT `fk_review_product1`
    FOREIGN KEY (`code`)
    REFERENCES `mydb`.`product` (`code`)
  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `email` VARCHAR(320) PRIMARY KEY,
  `username` VARCHAR(30),
  `password` VARCHAR(20),
  `first_name` VARCHAR(50),
  `last_name` VARCHAR(50),
  `address` VARCHAR(255),
  `phone_number` VARCHAR(15),
  `last_login_time` TIMESTAMP
  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_address` (
  `email` VARCHAR(320) PRIMARY KEY,
  `street_address` VARCHAR(255),
  `address_line_optional` VARCHAR(100),
  `city` VARCHAR(100),
  `state` ENUM('AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY', 'DC', 'PR', 'VI', 'GU', 'MP', 'AS'),
  `postal_code` CHAR(5),
  CONSTRAINT `fk_user_address_user`
    FOREIGN KEY (`email`)
    REFERENCES `mydb`.`user` (`email`)
  )
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
