-- SQLite Script
-- Generated by ChatGPT
-- Date: 2023-09-27

-- Create the 'mydb' database (SQLite uses a file-based database)
ATTACH DATABASE 'mydb.sqlite' AS mydb;

-- Table 'user'
CREATE TABLE mydb."user" (
    "email" TEXT NOT NULL,
    "username" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "first_name" TEXT NOT NULL,
    "last_name" TEXT NOT NULL,
    "address" TEXT NOT NULL,
    "phone_number" TEXT NOT NULL,
    "last_login_time" DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_user" PRIMARY KEY ("email"),
    CONSTRAINT "UQ_Username" UNIQUE ("username")
);

-- Table 'product'
CREATE TABLE mydb."product" (
    "code" CHAR(12) NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "manufacturer" TEXT NOT NULL,
    "photo" TEXT,
    "price" NUMERIC(7,2) NOT NULL,
    "cost" NUMERIC(7,2) NOT NULL,
    "inventory_quantity" INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT "PK_product" PRIMARY KEY ("code")
);

-- Table 'review'
CREATE TABLE mydb."review" (
    "review_id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "review_text" TEXT NOT NULL,
    "review_time" DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Table 'payment_method'
CREATE TABLE mydb."payment_method" (
    "payment_id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL,
    "card_number" CHAR(16) NOT NULL,
    "expiry_date" CHAR(4) NOT NULL,
    "csc" CHAR(4) NOT NULL,
    "billing_address" TEXT NOT NULL
);

-- Table 'purchase'
CREATE TABLE mydb."purchase" (
    "purchase_id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "total_price" NUMERIC(13,2) NOT NULL DEFAULT 1,
    "purchase_time" DATETIME DEFAULT CURRENT_TIMESTAMP,
    "product_time" NUMERIC(7,2) NOT NULL,
    "product_quantity" INTEGER NOT NULL
);
