-- PostgreSQL Script
-- Generated by ChatGPT
-- Date: 2023-09-27

-- Drop the database if it already exists
DROP DATABASE IF EXISTS mydb;

-- Create the 'mydb' database
CREATE DATABASE mydb;

-- Connect to the 'mydb' database
\c mydb

-- Table 'user'
CREATE TABLE "user" (
    "email" VARCHAR(320) NOT NULL,
    "username" VARCHAR(30) NOT NULL,
    "password" VARCHAR(20) NOT NULL,
    "first_name" VARCHAR(50) NOT NULL,
    "last_name" VARCHAR(50) NOT NULL,
    "address" VARCHAR(255) NOT NULL,
    "phone_number" VARCHAR(15) NOT NULL,
    "last_login_time" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_user" PRIMARY KEY ("email"),
    CONSTRAINT "UQ_Username" UNIQUE ("username")
);

-- Table 'product'
CREATE TABLE "product" (
    "code" CHAR(12) NOT NULL,
    "name" VARCHAR(100) NOT NULL,
    "description" TEXT NOT NULL,
    "manufacturer" VARCHAR(100) NOT NULL,
    "photo" VARCHAR(1000),
    "price" NUMERIC(7,2) NOT NULL,
    "cost" NUMERIC(7,2) NOT NULL,
    "inventory_quantity" INT NOT NULL DEFAULT 0,
    CONSTRAINT "PK_product" PRIMARY KEY ("code")
);

-- Table 'review'
CREATE TABLE "review" (
    "review_id" SERIAL NOT NULL,
    "review_text" TEXT NOT NULL,
    "review_time" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_review" PRIMARY KEY ("review_id")
);

-- Table 'payment_method'
CREATE TABLE "payment_method" (
    "payment_id" SERIAL NOT NULL,
    "name" VARCHAR(30) NOT NULL,
    "card_number" CHAR(16) NOT NULL,
    "expiry_date" CHAR(4) NOT NULL,
    "csc" CHAR(4) NOT NULL,
    "billing_address" VARCHAR(255) NOT NULL,
    CONSTRAINT "PK_payment_method" PRIMARY KEY ("payment_id")
);

-- Table 'purchase'
CREATE TABLE "purchase" (
    "purchase_id" SERIAL NOT NULL,
    "total_price" NUMERIC(13,2) NOT NULL DEFAULT 1,
    "purchase_time" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "product_time" NUMERIC(7,2) NOT NULL,
    "product_quantity" INT NOT NULL,
    CONSTRAINT "PK_purchase" PRIMARY KEY ("purchase_id")
);
